
CATEGORIES = [
    'divertido',
    'serio',
    'inspirador',
    'motivacional',
    'educativo',
    'creativo',
    'reflexivo',
    'optimista',
    'filosófico',
    'emotivo',
    'esperanzador',
    'fantástico',
    'realista',
    'soñador',
    'perspicaz',
    'humilde',
    'intuitivo',
    'cuestionador',
    'visionario',
    'emponderador',
    'innovador',
    'experimental',
    'colaborativo',
    'poderoso',
    'curioso',
    'provocador',
    'resiliente',
    'intrigante',
    'motivador',
    'ambicioso',
    'inquisitivo',
    'visionario',
    'intrépido',
    'futurista',
    'apasionado',
    'altruista',
    'pionero',
    'visionario',
    'compasivo',
    'sofisticado',
    'audaz',
    'visionario',
    'analítico',
    'vanguardista',
    'autodidacta',
    'visionario',
    'vibrante',
    'visceral',
    'visionario',
    'influyente',
    'revolucionario',
    'adaptativo',
    'respetuoso',
    'intransigente',
    'visionario',
    'visionario',
    'equilibrado',
    'visionario',
    'práctico',
    'espontáneo',
    'tenaz',
    'independiente',
    'auténtico',
    'informativo',
    'rebelde',
    'sabio',
    'juguetón',
    'trascendental',
    'visionario',
    'refrescante',
    'sutil',
    'atrevido',
    'visionario',
    'lúdico',
    'insolente',
    'visionario',
    'visionario',
    'sofisticado',
    'visionario',
    'profundo',
    'impulsivo',
    'esperanzador',
    'visionario',
    'reflexivo',
    'visionario',
    'pacificador',
    'visionario',
    'ingenioso',
    'visionario',
    'visionario',
    'sagaz',
    'fascinante',
    'visionario',
    'visionario'
]

THEMES = [
    'Amor y relaciones',
    'Superación personal',
    'Innovación y tecnología',
    'Diversidad e inclusión',
    'Ambiente y sostenibilidad',
    'Salud mental y bienestar',
    'Educación y aprendizaje',
    'Justicia social y derechos humanos',
    'Arte y creatividad',
    'Desarrollo personal',
    'Emprendimiento y negocios',
    'Viajes y aventuras',
    'Familia y crianza',
    'Éxito y logros',
    'Filosofía y reflexión',
    'Deporte y actividad física',
    'Espiritualidad y mindfulness',
    'Historia y cultura',
    'Ciencia y descubrimientos',
    'Humor y entretenimiento',
    'Tecnología y futuro',
    'Liderazgo y gestión',
    'Música y ritmo',
    'Cine y televisión',
    'Alimentación y nutrición',
    'Moda y estilo',
    'Religión y creencias',
    'Política y gobierno',
    'Medios de comunicación y redes sociales',
    'Creatividad y expresión',
    'Ecología y conservación',
    'Aventura y exploración',
    'Ética y moral',
    'Inspiración y motivación',
    'Inclusión digital',
    'Trabajo en equipo',
    'Resiliencia y fortaleza',
    'Hobbies y pasatiempos',
    'Crecimiento personal',
    'Comunidad y colaboración',
    'Voluntariado y servicio social',
    'Economía y finanzas',
    'Psicología y mente',
    'Viajes en el tiempo',
    'Robótica y inteligencia artificial',
    'Astrología y esoterismo',
    'Literatura y escritura',
    'Riesgo y aventura',
    'Viajes espaciales',
    'Arquitectura y diseño',
    'Educación financiera',
    'Parejas y relaciones',
    'Exploración marina',
    'Ciudades del futuro',
    'Mitología y leyendas',
    'Viajes en solitario',
    'Relaciones intergeneracionales',
    'Paz y resolución de conflictos',
    'El futuro del trabajo',
    'Viajes en grupo',
    'Autoestima y confianza',
    'Nuevas formas de comunicación',
    'Empoderamiento femenino',
    'La mente del emprendedor',
    'Realidad virtual y aumentada',
    'Viajes interplanetarios',
    'El poder de la mente',
    'Educación virtual',
    'Viajes interdimensionales',
    'El poder de la imaginación',
    'Turismo sostenible',
    'Viajes en el tiempo',
    'Diseño de videojuegos',
    'El arte de la persuasión',
    'Viajes en el espacio',
    'Educación del futuro',
    'Tecnología wearable',
    'El destino del universo',
    'Ecoturismo',
    'La mente del artista',
    'Exploración del universo',
    'Viajes en el mar',
    'Viajes interestelares',
    'Aventuras en la selva',
    'El viaje del héroe',
    'Viajes a lugares remotos',
    'Viajes en el subconsciente',
    'Viajes en el tiempo y el espacio',
    'El viaje de la vida',
    'Exploración de mundos perdidos',
    'Viajes al centro de la Tierra'
]

def system_thinking(categorie, theme): 
    return  f"""\
Bienvenido al Generador de Frases.
Por favor, crea una frase para la categoría "{categorie}" y el tema "{theme}".
Tu objetivo es inspirar pensamientos positivos o fomentar la creatividad.
¡Sé creativo y recuerda mantener un tono respetuoso en tu frase!
"""